mode: upload #
owner: kli # owner

upload:
  data:
    image_path: /ssd/kli/data/did/whitebox/whitebox_quentin/val
    anno_path: /ssd/kli/data/did/whitebox/whitebox_quentin/annotations/instances_val_head_face.json
    type: train  # for train
    build_single_file: false  # this is for multi tar
    tmp_root: ./tmp

  #  val_data_config:
  #    label_type: ["bbox"]  # length should be 1
  #    labels: ["head_realface"]  # length should be 1
  #    camera: ["did"]  # length should be 1
  #    unique_key: ["first test"]  # use this or id to get val data, length should be 1

  train_data_config:
    camera: ["did"]
    label_type: ["bbox"]

  label_config:
    name: ["head", "face"]  # in sequence, body 1, head 2, face 3

  channel_config:
    name: ch00000  # useful only build_single_file, default ch00000

  customer_config:
    customer_type: ["mall"]  # mall store all
    name: ["WANDA"]  # WANDA ANTA CTF GENERAL

  scene_config:
    name: ["bj-tzwd"]  # bj-tzwd beijing-cytj
#
#
## for download
#download:
#  data:
#    group: detection # detection / face
#    dst_root: ./datasets
#    tmp_root: ./tmp
#
#  train_data_config:
#    camera: ["did"]
#    label_type: ["bbox"]
#
#  label_config:
#    name: ["body", "head"]
#
#  customer_config:
#    customer_type: ["all"]
#    name: ["GENERAL"]
#
#  scene_config:
#    name: ["general-general"]
#
#  channel_config: null
#
#  val_data_config:
#    id: [8]
#    # unique_key: ["shit"]
